@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_Account
POST {{baseUrl}}/account
Content-Type: application/json

{
    "name": "Edson",
    "email": "eds222@m4.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "marcelo@m4.com",
    "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova pergunta",
    "content": "Conteúdo da pergunta"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions
Authorization: Bearer {{authToken}}